
name: Scan for secrets

on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Dogfood
      uses: ./
      id: dogfood
      with:
        extra_args: --only-verified
